routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Auth::routes();
Route::group(['middleware'=>['auth']], function(){

    // Route::get('signout', 'WebController@destroy');
    // Root
    Route::get('/', 'SiteController@index');
    // Site
    Route::resource('site', 'SiteController');
    // Dashboard
    Route::group(['prefix'=>'dashboard'], function(){
    	// Asset Terlaris
    	Route::get('asset-best-selling', 'SiteController@assetReport')->name('site.asset-best-selling');
    	Route::post('asset-best-selling/data', 'SiteController@bestSellingAsset')->name('site.data-asset-best-selling');
    	Route::get('asset-best-selling/investor/{id}', 'SiteController@bestSellingAssetInvestor')->name('site.investor-asset-best-selling');
        Route::get('table/asset-best-selling/{id}', 'SiteController@dataTableInvestor')->name('table.investor-asset-best-selling');
    	
    	// Investor Tertinggi
    	Route::get('highest-investment', 'DashboardController@dashboardHighestInvestment')->name('dashboard.highest-investment');
    	Route::post('highest-investment/data', 'DashboardController@dataHighestInvestment')->name('dashboard.data-highest-investment');
    	Route::get('highest-investment/asset', 'DashboardController@assetHighestInvestment');
    	Route::get('table/highest-investment/{id}', 'DashboardController@tableHighestInvestmentAsset');

        /* --------------- MAIN DASHBOARD -------------------- */
        // Route::get()->name();
    });

    // Master
    Route::group(['prefix'=>'master'], function(){
        // Role
        Route::resource('role', 'SecRoleController');
        Route::get('table/role', 'SecRoleController@dataTable')->name('table.role');
        
        /* --------------- MEMBER -------------------- */
        Route::resource('member', 'MstMemberController');
        Route::get('table/member', 'MstMemberController@dataTable')->name('table.member');
        Route::get('table/memberlang/{id}', 'MstMemberController@memberLangTable')->name('table.memberlang');
        Route::get('member/lang/{id}', 'MstMemberController@newLanguage')->name('member.lang');
        Route::get('member/lang/edit/{id}', 'MstMemberController@editLanguage')->name('member.editlang');
        Route::get('member/lang/destroy/{id}', 'MstMemberController@destroyLanguage')->name('member.destroylang');
        Route::get('member/detail/{id}', 'MstMemberController@detail')->name('member.detail');
        Route::get('table/member-lang/{id}', 'MstMemberController@dataTableLang')->name('table.member-lang');
        Route::get('member/delete/{id}', 'MstMemberController@delete')->name('member.delete');
        Route::get('member/edit-language/{id}', 'MstMemberController@editLanguage')->name('member.edit-lang');
        
        /* --------------- CLASS -------------------- */
        Route::resource('class', 'MstClassController');
        Route::get('table/class', 'MstClassController@dataTable')->name('table.class');
        Route::get('table/class-detail/{id}', 'MstClassController@dataTableDetail')->name('table.class-detail');
        Route::post('class/fetch-language', 'MstClassController@fetchLanguage')->name('class.fetch-language');
        Route::get('class/remove-language/{id}', 'MstClassController@removeLanguage')->name('class.remove-lang');
        Route::get('class/edit-language/{id}', 'MstClassController@editLanguage')->name('class.edit-lang');
        Route::post('class/update-language/{id}', 'MstClassController@updateLanguage')->name('class.update-lang');
        Route::get('class/delete/{id}', 'MstClassController@delete')->name('class.delete');
        // Class Price
        Route::resource('class-price', 'MstClassPriceController');
        Route::get('table/class-price', 'MstClassPriceController@dataTable')->name('table.MstClassPrice');
        
        /* --------------- BANK -------------------- */
        Route::resource('bank', 'MstBankController');
        Route::get('table/bank', 'MstBankController@dataTable')->name('table.bank');

        // Asset Category
        Route::resource('asset-category', 'MstAssetCategoryController');
        Route::get('table/asset-category', 'MstAssetCategoryController@dataTable')->name('table.asset-category');
        Route::get('table/asset-category-detail/{id}', 'MstAssetCategoryController@dataTableDetail')->name('table.asset-category-detail');
        Route::get('asset-category/delete/{id}', 'MstAssetCategoryController@delete')->name('asset-category.delete');
        // Help / FAQ
        Route::resource('help', 'MstHelpController');
        Route::get('table/help', 'MstHelpController@dataTable')->name('table.help');
        Route::get('help/delete/{id}', 'MstHelpController@delete')->name('help.delete');
        Route::post('help/remove-image', 'MstHelpController@removeImage')->name('help.remove-image');
        Route::get('help/create-new/id/{id}/lg/{lg}','MstHelpController@createNew')->name('help.create-new');
        Route::post('help/store-new', 'MstHelpController@storeNew')->name('help.store-new');
        Route::get('help/edit-new/id/{id}','MstHelpController@editNew')->name('help.edit-new');
        Route::put('help/update-new/{id}', 'MstHelpController@updateNew')->name('help.update-new');
        
        /* --------------- EMPLOYEE -------------------- */
        Route::resource('employee', 'MstEmployeeController');
        Route::get('table/employee', 'MstEmployeeController@dataTable')->name('table.employee');
        Route::post('employee/fetch', 'MstEmployeeController@fetch')->name('employee.fetch');
        Route::get('employee/delete/{id}', 'MstEmployeeController@delete')->name('employee.delete');
        // Page
        Route::resource('page', 'MstPageController');
        Route::get('table/page', 'MstPageController@dataTable')->name('table.page');
        // Terms & Conditions
        Route::resource('terms-conds', 'MstTermsCondsController');
        Route::get('table/terms-conds', 'MstTermsCondsController@dataTable')->name('table.terms-conds');
        Route::get('table/terms-conds-lang/{id}', 'MstTermsCondsController@dataTableLang')->name('table.terms-conds-lang');
        Route::get('terms-conds/delete/{id}', 'MstTermsCondsController@delete')->name('terms-conds.delete');
        Route::get('terms-conds/detail/{id}', 'MstTermsCondsController@detail')->name('terms-conds.detail');
        Route::get('terms-conds/edit_detail/{id}', 'MstTermsCondsController@edit_detail')->name('terms-conds.edit_detail');
        
        /* --------------- BANNER -------------------- */
        Route::resource('banner', 'MstBannerController');
        Route::get('table/banner', 'MstBannerController@dataTable')->name('table.banner');
        Route::get('banner/setposition/{id}','MstBannerController@setposition')->name('banner.setposition');
        Route::get('banner/delete/{id}', 'MstBannerController@delete')->name('banner.delete');
        Route::post('banner/set','MstBannerController@set')->name('banner.set');
        Route::post('banner/fetch', 'MstBannerController@fetch')->name('banner.fetch');
        Route::get('banner/deletepos/b/{b}/p/{p}', 'MstBannerController@deleteposition')->name('banner.deletepos');
        Route::get('table/banner/position/{id}', 'MstBannerController@positionDataTable')->name('table.banner.position');
        Route::post('banner/get-position', 'MstBannerController@getPosition')->name('banner.get-position');
        Route::get('banner/create-new/id/{id}/lg/{lg}','MstBannerController@createNew')->name('banner.create-new');
        Route::post('banner/store-new', 'MstBannerController@storeNew')->name('banner.store-new');
        Route::get('banner/edit-new/id/{id}','MstBannerController@editNew')->name('banner.edit-new');
        Route::put('banner/update-new/{id}', 'MstBannerController@updateNew')->name('banner.update-new');

        // Position
        Route::resource('position', 'MstPositionController');
        Route::get('table/position', 'MstPositionController@dataTable')->name('table.position');
        
        /* --------------- ASSET -------------------- */
        Route::resource('asset', 'MstAssetController');
        Route::get('asset/create-new/id/{id}/lg/{lg}', 'MstAssetController@createNew')->name('asset.create-new');
        Route::post('asset/store-new', 'MstAssetController@storeNew')->name('asset.store-new');
        Route::get('asset/edit-new/id/{id}/lg/{lg}', 'MstAssetController@editNew')->name('asset.edit-new');
        Route::put('asset/update-new/{id}', 'MstAssetController@updateNew')->name('asset.update-new');
        Route::get('table/asset', 'MstAssetController@dataTable')->name('table.asset');
        Route::post('asset/fetch-attributes', 'MstAssetController@fetchAttributes')->name('asset.fetch-attributes');
        Route::post('asset/remove-image', 'MstAssetController@removeImage')->name('asset.remove-image');
        Route::post('asset/remove-attr', 'MstAssetController@removeAttr')->name('asset.remove-attr');
        Route::post('asset/set-featured', 'MstAssetController@setFeatured')->name('asset.set-featured');
        Route::get('asset/delete/{id}', 'MstAssetController@delete')->name('asset.delete');
        Route::get('asset/rating-pane/{id}', 'MstAssetController@ratingPane')->name('asset.rating-pane');
        Route::get('asset/asset-pane/{id}', 'MstAssetController@assetPane')->name('asset.asset-pane');
        Route::get('asset/comment-pane/{id}', 'MstAssetController@commentPane')->name('asset.comment-pane');

resources/views/master/asset/action.blade.php
<a href="{{ $url_show }}" class="btn btn-xs btn-primary" title="Detail "><i class="fa fa-search"></i></a>
<a href="{{ $url_edit }}" class="btn btn-xs btn-primary" title="Edit "><i class="fa fa-edit"></i></a>
<a href="{{ $url_destroy }}" class="btn-delete btn btn-xs btn-danger" title="Delete "><i class="fa fa-trash"></i></a>

resources/views/master/asset/create_new.blade.php
@extends('base.main')
@section('title') Asset @endsection
@section('page_icon') <i class="fa fa-cube"></i> @endsection
@section('page_title') Add Asset Description <i>({{ $language->language }})</i> @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
        	<a href="{{ route('asset.show', base64_encode($model->asset_id)) }}" class="btn btn-success" title="Detail Asset">
                <i class="fa fa-search"></i> Detail
            </a>
            <a href="{{ route('asset.index') }}" class="btn btn-success" title="Manage Asset">
                <i class="fa fa-list"></i> Manage
            </a>
        </div>
    </div>
@endsection

@section('content')
<div class="box box-solid">
    {!! Form::model($model, [
        'route' => 'asset.store-new',
        'method'=> 'post',
        'enctype'   => 'multipart/form-data'
    ]) !!}
    <div class="box-body">
        <div class="box-body">
            @if(count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                        <li>{{  $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            {!! Form::hidden('asset_id', $id, []) !!}

            <p class="note"><i>Fields with <span class="required">*</span> are required.</i></p>
            <div class="row">
                <div class="col-md-3">
            		<div class="form-group">
                        <label for="asset_name" class="control-label">Language</label>
                        <input type="text" name="bahasa" value="{{ $language->language }}" disabled="disabled" class="form-control">
                        {!! Form::hidden('code', $language->code, []) !!}
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="form-group">
                        <label for="asset_name" class="control-label">Name*</label>
                        {!! Form::text('asset_name', null, ['class'=>'form-control', 'id'=>'asset_name', 'required'=>'required']) !!}

                        @if($errors->has('asset_name'))
                            <span class="invalid-feedback" role="alert">
                                {{ $errors->first('asset_name') }}
                            </span>
                        @endif
                    </div>
            	</div>
            </div>
            <div class="row">
            	<div class="col-md-12">
            		<div class="form-group">
                        <label for="desc" class="control-label">Description</label>
                        {{-- {!! Form::textarea('desc', null, ['class'=>'form-control', 'id'=>'editor1', 'rows'=>4, 'required'=>'required']) !!} --}}
                        {!! Form::textarea('desc', null, ['class'=>'form-control', 'id'=>'editor1', 'rows'=>3]) !!}

                        @if($errors->has('desc'))
                            <span class="invalid-feedback" role="alert">
                                {{ $errors->first('desc') }}
                            </span>
                        @endif
                    </div>
            	</div>
            </div>
            <div class="row">
                <div class="col-md-4 col-md-offset-2">
                    <div class="form-group">
                        <label for="file_resume" class="control-label">Resume File</label>
                        {{-- {!! Form::file('file_resume', ['accept'=>'.pdf', 'required'=>'required']) !!} --}}
                        {!! Form::file('file_resume', ['accept'=>'.pdf']) !!}
                        <p style="font-style: italic;">Ext. File : <b>.pdf</b></p>
                        @if($errors->has('file_resume'))
                            <span class="invalid-feedback" role="alert">
                                {{ $errors->first('file_resume') }}
                            </span>
                        @endif
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="file_fiducia" class="control-label">Fiducia File*</label>
                        {{-- {!! Form::file('file_fiducia', ['accept'=>'.pdf', 'required'=>'required']) !!} --}}
                        {!! Form::file('file_fiducia', ['accept'=>'.pdf']) !!}
                        <p style="font-style: italic;">Ext. File : <b>.pdf</b></p>
                        @if($errors->has('file_fiducia'))
                            <span class="invalid-feedback" role="alert">
                                {{ $errors->first('file_fiducia') }}
                            </span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer">
        {!! Form::submit('Add', ['class'=>'btn btn-primary pull-right']) !!}
    </div>
    {!! Form::close() !!}
</div>
@endsection

resources/views/master/asset/detail.blade.php
@extends('base.main')
@section('title') Asset @endsection
@section('page_icon') <i class="fa fa-cube"></i> @endsection
@section('page_title') Detail Asset @endsection
@section('page_subtitle') detail @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
        	<a href="{{ route('asset.edit', base64_encode($model->id)) }}" class="btn btn-success" title="Edit Asset">
                <i class="fa fa-edit"></i> Update
            </a>
            <a href="{{ route('asset.delete', base64_encode($model->id)) }}" class="btn btn-danger btn-delete2" title="Delete">
                <i class="fa fa-trash"></i> Delete
            </a>
        	<a href="{{ route('asset.create') }}" class="btn btn-success" title="Create Asset">
                <i class="fa fa-plus"></i> Create
            </a>
            <a href="{{ route('asset.index') }}" class="btn btn-success" title="Manage Asset">
                <i class="fa fa-list"></i> Manage
            </a>
        </div>
    </div>
@endsection

@section('content')
@if( !$model->isLanguageComplete() )
<div class="alert alert-warning alert-dismissible">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
	<h4><i class="icon fa fa-warning"></i> Please add description for other language</h4>
	Asset won't be active if you not complete the description
</div>
@endif
<div class="nav-tabs-custom">
	<ul class="nav nav-tabs tabs-up" id="friends">
		<li>
			<a href="{{ route('asset.asset-pane', base64_encode($model->id) ) }}" data-target="#tab_asset" class="media_node active span" id="asset_tab" data-toggle="tabajax" rel="tooltip"><i class="fa fa-cubes"></i> Asset </a>
		</li>
		<li>
			<a href="{{ route('asset.rating-pane', base64_encode($model->id)) }}" data-target="#tab_rating" class="media_node span" id="rating_tab" data-toggle="tabajax" rel="tooltip"><i class="fa fa-star"></i> Rating</a>
		</li>
		<li>
			<a href="{{ route('asset.comment-pane', base64_encode($model->id)) }}" data-target="#tab_comment" class="media_node span" id="awaiting_request_tab" data-toggle="tabajax" rel="tooltip"><i class="fa fa-comment"></i> Comment</a>
		</li>
		<li>
			<a href="{{ route('asset.favorite-pane', base64_encode($model->id)) }}" data-target="#tab_favorit" class="media_node span" id="awaiting_request_tab" data-toggle="tabajax" rel="tooltip"><i class="fa fa-flag"></i> Favorite</a>
		</li>
		<li>
			<a href="{{ route('asset.investor-pane', base64_encode($model->id)) }}" data-target="#tab_investor" class="media_node span" id="awaiting_request_tab" data-toggle="tabajax_investor" rel="tooltip"><i class="fa fa-user"></i> Investor</a>
		</li>
	</ul>

	<div class="tab-content">
		<div class="tab-pane active" id="tab_asset"></div>
		<div class="tab-pane" id="tab_rating"></div>
		<div class="tab-pane" id="tab_comment"></div>
		<div class="tab-pane" id="tab_favorit"></div>
		<div class="tab-pane" id="tab_investor"></div>
	</div>
</div>
@endsection

@push('scripts')
<script>

	$('.active[data-toggle="tabajax"]').each(function(e) {
	    var $this = $(this),
	        loadurl = $this.attr('href'),
	        targ = $this.attr('data-target');

	    $.get(loadurl, function(data) {
	        $(targ).html(data);
	    });

	    $this.tab('show');
	    return false;
	});

	$('[data-toggle="tabajax"]').click(function(e) {
	    var $this = $(this),
	        loadurl = $this.attr('href'),
	        targ = $this.attr('data-target');

	    // if(!targ.hasChildNodes())
	    // {
		    $.get(loadurl, function(data) {
		        $(targ).html(data);
		    });
	    // }

	    $this.tab('show');
	    return false;
	});

	$('[data-toggle="tabajax_investor"]').click(function(e) {
	    var $this = $(this),
	        loadurl = $this.attr('href'),
	        targ = $this.attr('data-target');

	    $.get(loadurl, function(data) {
	        $(targ).html(data);

	        $('#datatable-investor').DataTable({
			    responsive : true,
			    processing : true,
			    serverSide : true,
			    pageLength : 20,
			    ajax: "{{ route('table.asset.investor', $model->id) }}",
			    columns: [
			        {data : 'investor', name : 'investor'},
			        {data : 'amount', name : 'amount'},
			        {data : 'tenor', name : 'tenor'},
			        {data : 'interest', name : 'interest'},
			        {data : 'daily_interest', name : 'daily_interest'},
			        {data : 'total_interest', name : 'total_interest'},
			        {data : 'status', name : 'status'}
			    ]
			});
	    });

	    $this.tab('show');
	    return false;
	});
</script>
@endpush

@push('css')
<style>
.featured {
	background: #008d4c;
}	
</style>
@endpush

resources/views/master/asset/index.blade.php
@extends('base.main')
@section('title') Asset @endsection
@section('page_icon') <i class="fa fa-cube"></i> @endsection
@section('page_title') Asset @endsection
@section('page_subtitle') list @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
            <a href="{{ route('asset.create') }}" class="btn btn-success" title="Create Asset">
                <i class="fa fa-plus"></i> Create
            </a>
        </div>
    </div>
@endsection

@section('content')
    <div class="box box-solid">
        {{-- <div class="box-header">
            <button class="btn btn-sm btn-danger btn-mass-delete"><i class="fa fa-trash"></i></button>
        </div> --}}
        <div class="box-body">
            <table id="datatable" class="table table-hover table-condensed">
                <thead>
                    <tr>
                        {{-- <th></th> --}}
                        {{-- <th>No</th> --}}
                        <th>Asset name</th>
                        <th>Category</th>
                        <th>Owner Name</th>
                        <th>Created By</th>
                        <th>Created Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $('#datatable').DataTable({
            responsive : true,
            processing : true,
            serverSide : true,
            pageLength : 20,
            ajax: "{{ route('table.asset') }}",
            columns: [
                // {data : 'checkbox', name : 'checkbox'},
                // {data : 'DT_Row_Index', name : 'id'},
                {data : 'asset_name', name : 'asset_name'},
                {data : 'category', name : 'category'},
                {data : 'owner_name', name : 'owner_name'},
                {data : 'created_by', name : 'created_by'},
                {data : 'created_at', name : 'created_at'},
                {data : 'action', name : 'action'}
            ]
        });
    </script>
@endpush

resources/views/master/asset/update_new.blade.php
@extends('base.main')
@section('title') Asset @endsection
@section('page_icon') <i class="fa fa-cube"></i> @endsection
@section('page_title') Edit Asset Description <i>({{ $language->language }})</i> @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
        	<a href="{{ route('asset.show', base64_encode($model->asset_id)) }}" class="btn btn-success" title="Detail Asset">
                <i class="fa fa-search"></i> Detail
            </a>
            <a href="{{ route('asset.index') }}" class="btn btn-success" title="Manage Asset">
                <i class="fa fa-list"></i> Manage
            </a>
        </div>
    </div>
@endsection

@section('content')
<div class="box box-solid">
    {!! Form::model($model, [
        'route' => ['asset.update-new', base64_encode($model->id) ],
        'method'=> 'put',
        'enctype'   => 'multipart/form-data'
    ]) !!}
    <div class="box-body">
        <div class="box-body">
            @if(count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                        <li>{{  $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <p class="note"><i>Fields with <span class="required">*</span> are required.</i></p>
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label for="asset_name" class="control-label">Language</label>
                        <input type="text" name="bahasa" value="{{ $language->language }}" disabled="disabled" class="form-control">
                        {!! Form::hidden('code', $language->code, []) !!}
                    </div>
                </div>
                <div class="col-md-9">
                    <div class="form-group">
                        <label for="asset_name" class="control-label">Name*</label>
                        {!! Form::text('asset_name', null, ['class'=>'form-control', 'id'=>'asset_name', 'required'=>'required']) !!}

                        @if($errors->has('asset_name'))
                            <span class="invalid-feedback" role="alert">
                                {{ $errors->first('asset_name') }}
                            </span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="desc" class="control-label">Description</label>
                        {{-- {!! Form::textarea('desc', $model->description, ['class'=>'form-control', 'id'=>'editor1', 'rows'=>4, 'required'=>'required']) !!} --}}
                        {!! Form::textarea('desc', $model->description, ['class'=>'form-control', 'id'=>'editor1', 'rows'=>3]) !!}

                        @if($errors->has('desc'))
                            <span class="invalid-feedback" role="alert">
                                {{ $errors->first('desc') }}
                            </span>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 col-md-offset-2">
                    <div class="form-group">
                        <label for="file_resume" class="control-label">Resume File</label>
                        @if($model->file_resume != '')
                        <p><a href="/files/asset/{{ $model->file_resume }}" target="_blank" class="btn btn-xs btn-primary"><i class="fa fa-download"></i> Download Resume File</a></p>
                        @endif
                        {!! Form::file('file_resume', ['accept'=>'.pdf']) !!}
                        <p style="font-style: italic;">Ext. File : <b>.pdf</b></p>
                        @if($errors->has('file_resume'))
                            <span class="invalid-feedback" role="alert">
                                {{ $errors->first('file_resume') }}
                            </span>
                        @endif
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        <label for="file_fiducia" class="control-label">Fiducia File</label>
                        @if($model->file_fiducia != '')
                        <p><a href="/files/asset/{{ $model->file_fiducia }}" target="_blank" class="btn btn-xs btn-primary"><i class="fa fa-download"></i> Download Fiducia File</a></p>
                        @endif
                        {!! Form::file('file_fiducia', ['accept'=>'.pdf']) !!}
                        <p style="font-style: italic;">Ext. File : <b>.pdf</b></p>
                        @if($errors->has('file_fiducia'))
                            <span class="invalid-feedback" role="alert">
                                {{ $errors->first('file_fiducia') }}
                            </span>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    <div class="box-footer">
        {!! Form::submit('Save', ['class'=>'btn btn-primary pull-right']) !!}
    </div>
    {!! Form::close() !!}
</div>
@endsection