routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Auth::routes();
Route::group(['middleware'=>['auth']], function(){

    // Route::get('signout', 'WebController@destroy');
    // Root
    Route::get('/', 'SiteController@index');
    // Site
    Route::resource('site', 'SiteController');
    // Dashboard
    Route::group(['prefix'=>'dashboard'], function(){
    	// Asset Terlaris
    	Route::get('asset-best-selling', 'SiteController@assetReport')->name('site.asset-best-selling');
    	Route::post('asset-best-selling/data', 'SiteController@bestSellingAsset')->name('site.data-asset-best-selling');
    	Route::get('asset-best-selling/investor/{id}', 'SiteController@bestSellingAssetInvestor')->name('site.investor-asset-best-selling');
        Route::get('table/asset-best-selling/{id}', 'SiteController@dataTableInvestor')->name('table.investor-asset-best-selling');
    	
    	// Investor Tertinggi
    	Route::get('highest-investment', 'DashboardController@dashboardHighestInvestment')->name('dashboard.highest-investment');
    	Route::post('highest-investment/data', 'DashboardController@dataHighestInvestment')->name('dashboard.data-highest-investment');
    	Route::get('highest-investment/asset', 'DashboardController@assetHighestInvestment');
    	Route::get('table/highest-investment/{id}', 'DashboardController@tableHighestInvestmentAsset');

        /* --------------- MAIN DASHBOARD -------------------- */
        // Route::get()->name();
    });

    // Master
    Route::group(['prefix'=>'master'], function(){
        // Role
        Route::resource('role', 'SecRoleController');
        Route::get('table/role', 'SecRoleController@dataTable')->name('table.role');
        
        /* --------------- MEMBER -------------------- */
        Route::resource('member', 'MstMemberController');
        Route::get('table/member', 'MstMemberController@dataTable')->name('table.member');
        Route::get('table/memberlang/{id}', 'MstMemberController@memberLangTable')->name('table.memberlang');
        Route::get('member/lang/{id}', 'MstMemberController@newLanguage')->name('member.lang');
        Route::get('member/lang/edit/{id}', 'MstMemberController@editLanguage')->name('member.editlang');
        Route::get('member/lang/destroy/{id}', 'MstMemberController@destroyLanguage')->name('member.destroylang');
        Route::get('member/detail/{id}', 'MstMemberController@detail')->name('member.detail');
        Route::get('table/member-lang/{id}', 'MstMemberController@dataTableLang')->name('table.member-lang');
        Route::get('member/delete/{id}', 'MstMemberController@delete')->name('member.delete');
        Route::get('member/edit-language/{id}', 'MstMemberController@editLanguage')->name('member.edit-lang');
        
        /* --------------- CLASS -------------------- */
        Route::resource('class', 'MstClassController');
        Route::get('table/class', 'MstClassController@dataTable')->name('table.class');
        Route::get('table/class-detail/{id}', 'MstClassController@dataTableDetail')->name('table.class-detail');
        Route::post('class/fetch-language', 'MstClassController@fetchLanguage')->name('class.fetch-language');
        Route::get('class/remove-language/{id}', 'MstClassController@removeLanguage')->name('class.remove-lang');
        Route::get('class/edit-language/{id}', 'MstClassController@editLanguage')->name('class.edit-lang');
        Route::post('class/update-language/{id}', 'MstClassController@updateLanguage')->name('class.update-lang');
        Route::get('class/delete/{id}', 'MstClassController@delete')->name('class.delete');
        // Class Price
        Route::resource('class-price', 'MstClassPriceController');
        Route::get('table/class-price', 'MstClassPriceController@dataTable')->name('table.MstClassPrice');
        
        /* --------------- BANK -------------------- */
        Route::resource('bank', 'MstBankController');
        Route::get('table/bank', 'MstBankController@dataTable')->name('table.bank');

        // Asset Category
        Route::resource('asset-category', 'MstAssetCategoryController');
        Route::get('table/asset-category', 'MstAssetCategoryController@dataTable')->name('table.asset-category');
        Route::get('table/asset-category-detail/{id}', 'MstAssetCategoryController@dataTableDetail')->name('table.asset-category-detail');
        Route::get('asset-category/delete/{id}', 'MstAssetCategoryController@delete')->name('asset-category.delete');
        // Help / FAQ
        Route::resource('help', 'MstHelpController');
        Route::get('table/help', 'MstHelpController@dataTable')->name('table.help');
        Route::get('help/delete/{id}', 'MstHelpController@delete')->name('help.delete');
        Route::post('help/remove-image', 'MstHelpController@removeImage')->name('help.remove-image');
        Route::get('help/create-new/id/{id}/lg/{lg}','MstHelpController@createNew')->name('help.create-new');
        Route::post('help/store-new', 'MstHelpController@storeNew')->name('help.store-new');
        Route::get('help/edit-new/id/{id}','MstHelpController@editNew')->name('help.edit-new');
        Route::put('help/update-new/{id}', 'MstHelpController@updateNew')->name('help.update-new');
        
        /* --------------- EMPLOYEE -------------------- */
        Route::resource('employee', 'MstEmployeeController');
        Route::get('table/employee', 'MstEmployeeController@dataTable')->name('table.employee');
        Route::post('employee/fetch', 'MstEmployeeController@fetch')->name('employee.fetch');
        Route::get('employee/delete/{id}', 'MstEmployeeController@delete')->name('employee.delete');
        // Page
        Route::resource('page', 'MstPageController');
        Route::get('table/page', 'MstPageController@dataTable')->name('table.page');
        // Terms & Conditions
        Route::resource('terms-conds', 'MstTermsCondsController');
        Route::get('table/terms-conds', 'MstTermsCondsController@dataTable')->name('table.terms-conds');
        Route::get('table/terms-conds-lang/{id}', 'MstTermsCondsController@dataTableLang')->name('table.terms-conds-lang');
        Route::get('terms-conds/delete/{id}', 'MstTermsCondsController@delete')->name('terms-conds.delete');
        Route::get('terms-conds/detail/{id}', 'MstTermsCondsController@detail')->name('terms-conds.detail');
        Route::get('terms-conds/edit_detail/{id}', 'MstTermsCondsController@edit_detail')->name('terms-conds.edit_detail');
        
        /* --------------- BANNER -------------------- */
        Route::resource('banner', 'MstBannerController');
        Route::get('table/banner', 'MstBannerController@dataTable')->name('table.banner');
        Route::get('banner/setposition/{id}','MstBannerController@setposition')->name('banner.setposition');
        Route::get('banner/delete/{id}', 'MstBannerController@delete')->name('banner.delete');
        Route::post('banner/set','MstBannerController@set')->name('banner.set');
        Route::post('banner/fetch', 'MstBannerController@fetch')->name('banner.fetch');
        Route::get('banner/deletepos/b/{b}/p/{p}', 'MstBannerController@deleteposition')->name('banner.deletepos');
        Route::get('table/banner/position/{id}', 'MstBannerController@positionDataTable')->name('table.banner.position');
        Route::post('banner/get-position', 'MstBannerController@getPosition')->name('banner.get-position');
        Route::get('banner/create-new/id/{id}/lg/{lg}','MstBannerController@createNew')->name('banner.create-new');
        Route::post('banner/store-new', 'MstBannerController@storeNew')->name('banner.store-new');
        Route::get('banner/edit-new/id/{id}','MstBannerController@editNew')->name('banner.edit-new');
        Route::put('banner/update-new/{id}', 'MstBannerController@updateNew')->name('banner.update-new');

        // Position
        Route::resource('position', 'MstPositionController');
        Route::get('table/position', 'MstPositionController@dataTable')->name('table.position');
        
        /* --------------- ASSET -------------------- */
        Route::resource('asset', 'MstAssetController');
        Route::get('asset/create-new/id/{id}/lg/{lg}', 'MstAssetController@createNew')->name('asset.create-new');
        Route::post('asset/store-new', 'MstAssetController@storeNew')->name('asset.store-new');
        Route::get('asset/edit-new/id/{id}/lg/{lg}', 'MstAssetController@editNew')->name('asset.edit-new');
        Route::put('asset/update-new/{id}', 'MstAssetController@updateNew')->name('asset.update-new');
        Route::get('table/asset', 'MstAssetController@dataTable')->name('table.asset');
        Route::post('asset/fetch-attributes', 'MstAssetController@fetchAttributes')->name('asset.fetch-attributes');
        Route::post('asset/remove-image', 'MstAssetController@removeImage')->name('asset.remove-image');
        Route::post('asset/remove-attr', 'MstAssetController@removeAttr')->name('asset.remove-attr');
        Route::post('asset/set-featured', 'MstAssetController@setFeatured')->name('asset.set-featured');
        Route::get('asset/delete/{id}', 'MstAssetController@delete')->name('asset.delete');
        Route::get('asset/rating-pane/{id}', 'MstAssetController@ratingPane')->name('asset.rating-pane');
        Route::get('asset/asset-pane/{id}', 'MstAssetController@assetPane')->name('asset.asset-pane');
        Route::get('asset/comment-pane/{id}', 'MstAssetController@commentPane')->name('asset.comment-pane');

resources/views/master/member/action-detail.blade.php
<a href="{{ $url_edit }}" class="btn btn-xs btn-primary" title="Edit {{ $model->description }}"><i class="fa fa-edit"></i></a>

resources/views/master/member/action.blade.php
<a href="{{ $url_show }}" class="btn btn-xs btn-primary" title="Detail {{ $model->description }}"><i class="fa fa-search"></i></a>
<a href="{{ $url_edit }}" class="btn btn-xs btn-primary edit" title="Edit {{ $model->description }}"><i class="fa fa-edit"></i></a>
<a href="{{ $url_destroy }}" class="btn-delete btn btn-xs btn-danger" title="Delete {{ $model->description }}"><i class="fa fa-trash"></i></a>

resources/views/master/member/create.blade.php
@extends('base.main')
@section('title') Member @endsection
@section('page_icon') <i class="fa fa-book"></i> @endsection
@section('page_title') Member @endsection
@section('page_subtitle') create @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
            <a href="{{ route('member.index') }}" class="btn btn-default"><i class="fa fa-list"></i> Manage</a>
        </div>
    </div>
@endsection

@section('content')
<div class="box box-solid">
    {!! Form::model($model, [
        'route' => 'member.store',
        'method'=> 'post',
        'enctype'   => 'multipart/form-data'
    ]) !!}

    <div class="box-body">
        <div class="box-body">
            @if(count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach($errors->all() as $error)
                        <li>{{  $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            @php $no = 0; @endphp
            @foreach($language as $r)
                <div class="box-body row">
                    <div class="col-md-2">
                        <div class="form-group">
                            @if($no < 1) <label for="code" class="control-label">Language</label> @endif
                            <input type="text" name="bahasa" value="{{ $r->language }}" disabled="disabled" class="form-control">
                            {!! Form::hidden('code[]', $r->code, []) !!}
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            @if($no < 1)<label for="description" class="control-label">Name*</label> @endif
                            {!! Form::text('description[]', null, ['class'=>'form-control', 'id'=>'description', 'required'=>'required']) !!}

                            @if($errors->has('description.*'))
                                <span class="invalid-feedback" role="alert">
                                    {{ $errors->first('description.*') }}
                                </span>
                            @endif
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            @if($no < 1)<label for="image" class="control-label">Icon*</label> @endif
                            {!! Form::file('image[]', ['accept'=>'image/x-png, image/jpeg, image/jpg', 'required'=>'required']) !!}

                            @if($errors->has('image.*'))
                                <span class="invalid-feedback" role="alert">
                                    {{ $errors->first('image.*') }}
                                </span>
                            @endif
                        </div>
                    </div>
                </div>
                @php $no++; @endphp
            @endforeach

            <hr>
            <div class="box-body">
                <div class="form-group">
                    <label for="code" class="control-label">Active</label>
                    <div>
                        {!! Form::checkbox('active', null, null, ['id'=>'active']) !!} 
                    </div>
                    @if($errors->has('active'))
                        <span class="invalid-feedback" role="alert">
                            {{ $errors->first('active') }}
                        </span>
                    @endif
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer">
        {!! Form::submit('Create', ['class'=>'btn btn-primary pull-right']) !!}
    </div>

    {!! Form::close() !!}
</div>
@endsection

resources/views/master/member/detail.blade.php
@extends('base.main')
@section('title') Member @endsection
@section('page_icon') <i class="fa fa-user"></i> @endsection
@section('page_title') Detail Member @endsection

@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
            <a href="{{ route('member.edit', base64_encode($model->id)) }}" class="btn btn-success" title="Edit member">
                <i class="fa fa-edit"></i> Edit
            </a>
            <a href="{{ route('member.delete', base64_encode($model->id)) }}" class="btn btn-danger btn-delete2" title="Delete">
                <i class="fa fa-trash"></i> Delete
            </a>
            <a href="{{ route('member.create') }}" class="btn btn-success" title="Create member">
                <i class="fa fa-plus"></i> Create
            </a>
            <a href="{{ route('member.index') }}" class="btn btn-success" title="Manage member">
                <i class="fa fa-list"></i> Manage
            </a>
        </div>
    </div>
@endsection

@section('content')
<div class="box box-solid">
    <div class="box-body">
        <div class="box-body">
            <table id="datatable" class="table table-hover table-condensed">
                <thead>
                    <tr>
                        <th width="50px">No</th>
                        <th>Language</th>
                        <th>Name</th>
                        <th width="200px">Icon</th>
                        {{-- <th width="60px">Action</th> --}}
                    </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script>
        $('#datatable').DataTable({
            responsive : true,
            processing : true,
            serverSide : true,
            ajax: "{{ route('table.memberlang', base64_encode($model->id)) }}",
            columns: [
                {data : 'DT_Row_Index', name : 'id'},
                {data : 'language', name : 'language'},
                {data : 'description', name : 'description'},
                {data : 'image', name : 'image'},
            ]
        });
    </script>
@endpush

resources/views/master/member/edit.blade.php
@extends('base.main')
@section('title') Member @endsection
@section('page_icon') <i class="fa fa-user"></i> @endsection
@section('page_title') Edit Member @endsection

@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
            <a href="{{ route('member.show', base64_encode($model->id)) }}" class="btn btn-success" title="Detail Member">
                <i class="fa fa-search"></i> Detail
            </a>
            <a href="{{ route('member.delete', base64_encode($model->id)) }}" class="btn btn-danger btn-delete2" title="Delete">
                <i class="fa fa-trash"></i> Delete
            </a>
            <a href="{{ route('member.create') }}" class="btn btn-success" title="Create Member">
                <i class="fa fa-plus"></i> Create
            </a>
            <a href="{{ route('member.index') }}" class="btn btn-success" title="Manage Member">
                <i class="fa fa-list"></i> Manage
            </a>
        </div>
    </div>
@endsection

@section('content')
<div class="box box-solid">
    {!! Form::model($model, [
        'route' => ['member.update', base64_encode($model->id)],
        'method'=> 'put',
        'enctype'   => 'multipart/form-data'
    ]) !!}

    <div class="box-body">
        @if(count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                    <li>{{  $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        @php $no = 0; @endphp
        @foreach($data as $key => $r)

            {!! Form::hidden('id[]', $r->id, []) !!}
            <div class="box-body row">
                <div class="col-md-2">
                    <div class="form-group">
                        @if($no < 1) <label for="code" class="control-label">Language</label> @endif
                        <input type="text" name="bahasa" value="{{ $r->language }}" disabled="disabled" class="form-control">
                        {!! Form::hidden('code[]', $r->code, []) !!}
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @if($no < 1)<label for="description" class="control-label">Name*</label> @endif
                        {!! Form::text('description[]', $r->description, ['class'=>'form-control', 'id'=>'description', 'required'=>'required']) !!}

                        @if($errors->has('description.*'))
                            <span class="invalid-feedback" role="alert">
                                {{ $errors->first('description.*') }}
                            </span>
                        @endif
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        @if($no < 1) <img src="\images\member\{{ $r->image }}" width="50px" style="margin-top: 25px;" /> 
                        @else <img src="\images\member\{{ $r->image }}" width="50px" /> 
                        @endif
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @if($no < 1)<label for="image" class="control-label">Icon</label> @endif
                        {!! Form::file('image[]', ['accept'=>'image/x-png, image/jpeg, image/jpg']) !!}

                        @if($errors->has('image'))
                            <span class="invalid-feedback" role="alert">
                                {{ $errors->first('image') }}
                            </span>
                        @endif
                    </div>
                </div>
            </div>

            @php $no++; @endphp
        @endforeach

        <hr>
        <div class="box-body">
            <div class="form-group">
                <label for="code" class="control-label">Active</label>
                <div>
                    {!! Form::checkbox('active', null, null, ['id'=>'active']) !!} 
                </div>
                @if($errors->has('active'))
                    <span class="invalid-feedback" role="alert">
                        {{ $errors->first('active') }}
                    </span>
                @endif
            </div>
        </div>
    </div>
    <div class="box-footer">
        {!! Form::submit('Save', ['class'=>'btn btn-primary pull-right']) !!}
    </div>
    {!! Form::close() !!}
</div>
@endsection

@push('scripts')
<script>
    
</script>
@endpush

resources/views/master/member/form.blade.php
@php
    $method = $model->exists ? 'PUT' : 'POST';
@endphp
{!! Form::model($model, [
    'route' => $model->exists ? ['member.update', $model->id] : 'member.store',
    'method'=> $method,
]) !!}

    <div class="form-group">
        <label for="code" class="control-label">Language</label>
        {!! Form::select('code', [''=>'- Select -'] + $lang, 'IND', ['class'=>'form-control',' id'=>'code', 'disabled'=>'disabled']) !!}
    </div>

    <div class="form-group">
        <label for="description" class="control-label">Name</label>
        {!! Form::text('description', null, ['class'=>'form-control', 'id'=>'description']) !!}
    </div>

    {{-- <div class="form-group">
        <label for="active" class="control-label">Active</label>
        <div>
            {!! Form::checkbox('active', null, null, ['id'=>'active']) !!} 
        </div>
    </div> --}}

{!! Form::close() !!}

resources/views/master/member/index.blade.php
@extends('base.main')
@section('title') Member @endsection
@section('page_icon') <i class="fa fa-user"></i> @endsection
@section('page_title') Member @endsection
@section('page_subtitle') list @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
            <a href="{{ route('member.create') }}" class="btn btn-success" title="Create Member">
                <i class="fa fa-plus"></i> Create
            </a>
        </div>
    </div>
@endsection

@section('content')
    <div class="box box-solid">
        {{-- <div class="box-header">
            <button class="btn btn-sm btn-danger btn-mass-delete"><i class="fa fa-trash"></i></button>
        </div> --}}
        <div class="box-body">
            <div class="box-body">
                <table id="datatable" class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            {{-- <th></th> --}}
                            <th width="5%">No</th>
                            <th>Name</th>
                            <th>Logo</th>
                            <th width="10%">Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $('#datatable').DataTable({
            responsive : true,
            processing : true,
            serverSide : true,
            ajax: "{{ route('table.member') }}",
            columns: [
                // {data : 'checkbox', name : 'checkbox'},
                {data : 'DT_Row_Index', name : 'id'},
                {data : 'description', name : 'description'},
                {data : 'image', name : 'image'},
                {data : 'action', name : 'action'}
            ]
        });
    </script>
@endpush