routes/web.php
        Route::get('atm/edit/{id}', 'InvestorAtmController@edit')->name('atm.edit');
        Route::put('atm/update/{id}', 'InvestorAtmController@update')->name('atm.update');
        Route::get('atm/destroy/{id}', 'InvestorAtmController@destroy')->name('atm.destroy');
        /* --------------- INVESTOR / BALANCE -------------------- */
	    Route::get('balance/balance-pane', 'InvestorBalanceController@pane')->name('balance.pane');
	    Route::get('table/balance/{id}', 'InvestorBalanceController@dataTable')->name('table.balance');
        Route::get('balance/get/{id}', 'InvestorBalanceController@getBalance')->name('balance.get');
        Route::get('balance/topup-form/{id}', 'InvestorBalanceController@topupForm')->name('balance.topup-form');
        Route::post('balance/topup', 'InvestorBalanceController@topup')->name('balance.topup');
        Route::get('balance/cashout-form/{id}', 'InvestorBalanceController@cashoutForm')->name('balance.cashout-form');
        // Investor -> transaction
	    Route::get('transaction/transaction-pane', 'InvestorTransactionController@pane')->name('transaction.pane');
	    Route::get('table/transaction/{id}', 'InvestorTransactionController@dataTable')->name('table.transaction');
        // Investor -> asset
        Route::get('investor-asset/asset-pane', 'InvestorAssetController@assetPane')->name('investor-asset.pane');
	    Route::get('table/investor-asset/{id}', 'InvestorAssetController@assetDataTable')->name('table.investor-asset');
        Route::get('investor-asset/detail/{id}', 'InvestorAssetController@assetDetail')->name('investor-asset.detail');
        // Investor -> asset fav
        Route::get('investor-asset/fav-asset-pane', 'InvestorAssetController@assetFavPane')->name('investor-asset-fav.pane');
	    Route::get('table/investor-asset-fav/{id}', 'InvestorAssetController@assetFavDataTable')->name('table.investor-asset-fav');

        /* --------------- MONITORING TOPUP -------------------- */
        Route::resource('monitoring-topup', 'MonitoringtopupController');
        Route::get('table/monitoring-topup', 'MonitoringtopupController@dataTable')->name('table.MonitoringTopup');
	    Route::get('table/monitoring-topup-history/{id}', 'MonitoringtopupController@dataHistory')->name('table.topup.history');
        Route::get('monitoring-topup/verify/{id}', 'MonitoringtopupController@verify')->name('monitoring-topup.verify');
        Route::post('monitoring-topup/reject', 'MonitoringtopupController@reject')->name('monitoring-topup.reject');
        Route::get('widget/monitoring-topup', 'MonitoringtopupController@reloadWidget')->name('monitoring-topup.widget');
        Route::post('monitoring-topup/recheck', 'MonitoringtopupController@recheck')->name('monitoring-topup.recheck');

        /* --------------- MONITORING CASH OUT -------------------- */
        Route::resource('monitoring-cashout', 'MonitoringTopupOutController');
        Route::get('table/monitoring-cashout', 'MonitoringTopupOutController@dataTable')->name('table.MonitoringTopupOut');
        Route::get('table/monitoring-cashout-history/{id}', 'MonitoringTopupOutController@dataHistory')->name('table.cashout.history');
        Route::get('monitoring-cashout/process/{id}', 'MonitoringTopupOutController@process')->name('monitoring-cashout.process');
        Route::get('monitoring-cashout/verify/{id}', 'MonitoringTopupOutController@verify')->name('monitoring-cashout.verify');
        Route::post('monitoring-cashout/reject', 'MonitoringTopupOutController@reject')->name('monitoring-cashout.reject');
        Route::get('widget/monitoring-cashout', 'MonitoringTopupOutController@reloadWidget')->name('monitoring-cashout.widget');
        
        /* --------------- OFFERING PURCHASE -------------------- */
        Route::resource('offering-purchase', 'OfferingPurchaseController');
        Route::get('table/offering-purchase', 'OfferingPurchaseController@dataTable')->name('table.offering-purchase');
        Route::get('offering-purchase/reply/{id}', 'OfferingPurchaseController@reply')->name('offering-purchase.reply');
    });
        
    // Setting
    Route::group(['prefix'=>'setting'], function(){
       // Module
        Route::resource('menu', 'SecModuleController');
        Route::get('table/menu', 'SecModuleController@dataTable')->name('table.SecModule');
        //Access Level
		Route::resource('access-level', 'SecAccessLevelController');
		Route::get('table/access-level', 'SecAccessLevelController@dataTable')->name('table.access-level'); 
		Route::get('table/detail-access-level', 'SecAccessLevelController@dataTableDetail')->name('table.detail-access-level');
		Route::post('access-level/add-act', 'SecAccessLevelController@addAct')->name('access-level.add-act'); 
		Route::post('access-level/remove-act', 'SecAccessLevelController@removeAct')->name('access-level.remove-act'); 
    });
	
	// Route::get('/master/country','CountryController@index');
	// Route::get('/master/country/create','CountryController@create');
	// Route::post('/master/country/post_country','CountryController@store');
	// Route::get('/master/country/edit/{id}','CountryController@edit');
	// Route::post('/master/country/edit_country/{id}','CountryController@update');
	// Route::get('/master/country/import','CountryController@import');
	// Route::post('/master/country/proses_import','CountryController@proses_import');

	Route::get('/master/province','ProvinceController@index');
	Route::get('/master/province/create','ProvinceController@create');
	Route::post('/master/province/post_province','ProvinceController@store');
	Route::post('/master/province/edit_province/{id}','ProvinceController@update');
	Route::get('/master/province/delete/{id}','ProvinceController@destroy');
	Route::get('/master/province/edit/{id}','ProvinceController@edit');
	Route::get('/master/province/delete/{id}','ProvinceController@destroy');
	Route::get('/master/province/import','ProvinceController@import');
	Route::post('/master/province/import_province','ProvinceController@import_province');
	
	/*Route::get('/master/regency','RegencyController@index');
	Route::get('/master/regency/create','RegencyController@create');
	Route::post('/master/regency/post_regency','RegencyController@store');
	Route::get('/master/regency/edit_regency/{id}','RegencyController@edit');
	Route::post('/master/regency/regency_edit/{id}','RegencyController@update');
	Route::get('/master/regency/delete_regency/{id}','RegencyController@destroy');
	Route::post('/master/regency/regency_edit/{id}','RegencyController@update');
	Route::get('/master/regency/import','RegencyController@import');
	Route::post('/master/regency/import_post_regency','RegencyController@import_regency');*/

	
	Route::get('/master/data_address','MstAddressController@index');
	Route::get('/master/address/create','MstAddressController@create');
	Route::get('/master/address/province/{id}','MstAddressController@province');
	Route::get('/master/address/regency/{id}','MstAddressController@regency');
	Route::get('/master/address/district/{id}','MstAddressController@district');
	Route::get('/master/address/village/{id}','MstAddressController@village');
	Route::post('/master/address/post_address','MstAddressController@store');

	/* --------------- MONITORING CASH OUT -------------------- */
	// Route::resource('master/category-news', 'MstNewsCategoryController');
	// Route::get('table/category-news', 'MstNewsCategoryController@dataTable')->name('table.BlgCategoryNews');
	// Route::resource('master/category-news', 'BlgCategoryNewsController');
	// Route::get('table/category-news', 'BlgCategoryNewsController@dataTable')->name('table.BlgCategoryNews');
	
	// Blg News
	// Route::resource('master/news', 'BlgNewsController');
	// Route::get('table/news', 'BlgNewsController@dataTable')->name('table.BlgNews');
	// Route::get('news/setposition/{id}','BlgNewsController@setposition')->name('banner/bannerposition');
	// Route::get('news/delete/{id}', 'BlgNewsController@delete')->name('news.delete');
	
	

	//Contact Us
	// Route::resource('master/contact-us', 'MstContactUsController');
	// Route::get('table/contact-us', 'MstContactUsController@dataTable')->name('table.MstContactUs');
	
	//Tag News
	// Route::resource('master/tag-news', 'MstTagNewsController');
	// Route::get('table/tag-news', 'MstTagNewsController@dataTable')->name('table.MstTagNews');

	Route::resource('master/class-price', 'MstClassPriceController');
	Route::get('table/class-price', 'MstClassPriceController@dataTable')->name('table.MstClassPrice');

	

	// Route::resource('master/security-guide', 'SecurityGuideController');
	// Route::get('table/security-guide', 'SecurityGuideController@dataTable')->name('table.SecurityGuide');
	// Route::get('security-guide/delete/{id}', 'SecurityGuideController@delete')->name('security-guide.delete');
 //    Route::get('security-guide/show-detail/{id}', 'SecurityGuideController@show_detail')->name('security-guide.show-detail');
 //    Route::put('security-guide/update-data/{id}', 'SecurityGuideController@updateData')->name('security-guide.update-data');

	// Route::resource('master/partner', 'MstPartnerController');
	// Route::get('table/partner', 'MstPartnerController@dataTable')->name('table.MstPartner');
	// Route::get('partner/delete/{id}', 'MstPartnerController@delete')->name('partner.delete');

	Route::resource('master/voucher', 'MstVoucherController');
	Route::get('table/voucher', 'MstVoucherController@dataTable')->name('table.MstVoucher');
	Route::get('voucher/delete/{id}', 'MstVoucherController@delete')->name('voucher.delete');
    Route::get('voucher/detail/{id}', 'MstVoucherController@detail')->name('voucher.detail');
    Route::get('voucher/edit_detail/{id}', 'MstVoucherController@edit_detail')->name('voucher.edit_detail');
    Route::get('voucher/show-detail/{id}', 'MstVoucherController@show_detail')->name('voucher.show-detail');
    Route::put('voucher/update-satu/{id}', 'MstVoucherController@update_satu')->name('voucher.update-satu');

});

resources/views/setting/access-level/action.blade.php
<a href="{{ $url_show }}" class="btn btn-xs btn-primary" title="Detail {{ $model->role }}"><i class="fa fa-search"></i></a>

resources/views/setting/access-level/detail.blade.php
@extends('base.main')
@section('title') Access Role @endsection
@section('page_icon') <i class="fa fa-cog"></i> @endsection
@section('page_title') Detail Access Role @endsection
@section('page_subtitle') list @endsection
@section('menu')
    <div class="box box-solid" style="text-align:right;">
        <div class="box-body">
            <a href="{{ route('access-level.index') }}" class="btn btn-success" title="Manage Access Role">
                <i class="fa fa-list"></i> Manage
            </a>
        </div>
    </div>
@endsection

@section('content')
<div class="box box-solid">
	<div class="box-body">
		<div class="box-body">
			<h4>Role : <strong>{{ $role->role }}</strong></h4>
			<table id="datatable" class="table table-hover table-condensed table-bordered">
	            <thead>
	            	<tr>
	            		<th width="50px">No</th>
	            		<th>Module</th>
	            		<th>Read</th>
	            		<th>Create</th>
	            		<th>Update</th>
	            		<th>Delete</th>
	            		<th>Show</th>
	            	</tr>
	            </thead>
	            @php
	            	$no = 1;
	            	$action = ['R','C','U','D','S']; 
	            @endphp
	            <tbody>
	            	@foreach($modules as $module)
		            	<tr>
		            		<td>{{ $no++ }}</td>
		            		<td><strong>{{ $module->module }}</strong></td>
		            		@for($a = 0; $a < count($action); $a++)
		            			@php $checked = false; @endphp
		            			@if($model->isActionChecked($module->id, $action[$a], $actions))
		            				@php $checked = true; @endphp
		            			@endif
		            			<td width="100px" style="text-align: center;">
		            				@if($model->isHasChild($module->id) > 0 && in_array($action[$a], ['R','C','U','D']))
		            					@php continue; @endphp
		            				@endif
		            				<input type="checkbox" class="checkbox_act" data-role="{{ $role->id }}" data-module="{{ $module->id }}" data-act="{{ $action[$a] }}" {{ $checked ? "checked" : "" }}>
		            			</td>	
		            		@endfor
		            	</tr>
	            		@if($module->parent_id == null)
	            			@foreach($model->getModuleChild($module->id) as $child)
	            			<tr>
	            				<td>{{ $no++ }}</td>
			            		<td style="padding-left: 30px;">{{ $child->module }}</td>

			            		@for($b = 0; $b < count($action); $b++)
			            			@php $checked = false; @endphp
			            			@if($model->isActionChecked($child->id, $action[$b], $actions))
			            				@php $checked = true; @endphp
			            			@endif
			            			<td width="100px" style="text-align: center;">
			            				@if($model->isHasChild($child->id) > 0 && in_array($action[$b], ['R','C','U','D']))
			            					@php continue; @endphp
			            				@endif
				            			<input type="checkbox" class="checkbox_act" data-role="{{ $role->id }}" data-module="{{ $child->id }}" data-act="{{ $action[$b] }}" {{ $checked ? "checked" : "" }}>
				            		</td>
			            		@endfor	
	            			</tr>
	            			@php
	            				$child_second = $model->getModuleChild($child->id);
	            			@endphp
	            			@if($child_second != null)
	            				@foreach($child_second as $child2)
		            			<tr>
		            				<td>{{ $no++ }}</td>
				            		<td style="padding-left: 60px;">{{ $child2->module }}</td>

				            		@for($c = 0; $c < count($action); $c++)
				            			@php $checked = false; @endphp
				            			@if($model->isActionChecked($child2->id, $action[$c], $actions))
				            				@php $checked = true; @endphp
				            			@endif
				            			<td width="100px" style="text-align: center;">
					            			<input type="checkbox" class="checkbox_act" data-role="{{ $role->id }}" data-module="{{ $child2->id }}" data-act="{{ $action[$c] }}" {{ $checked ? "checked" : "" }}>
					            		</td>
				            		@endfor
		            			</tr>
	            				@endforeach
	            			@endif
	            			@endforeach
	            		@endif
	            	@endforeach
	            </tbody>
	        </table>
		</div>
	</div>
</div>
@endsection

@push('scripts')
<script>

	$('.checkbox_act').on('click', function(){
		var role = $(this).data('role'),
			module = $(this).data('module'),
			act = $(this).data('act'),
			token = $('meta[name="csrf-token"]').attr('content');

		var action = '';
		if(act == 'R')
			action = 'Read';
		else if(act == 'C')
			action = 'Create';
		else if(act == 'U')
			action = 'Update';
		else if(act == 'D')
			action = 'Delete';
		else if(act == 'S')
			action = 'Show';
		else
			action = 'Unknown';

		if($(this).is(":checked")) 
		{
			// alert('checked '+role+'-'+module+'-'+act);
			$.ajax({
				url : "{{ route('access-level.add-act') }}",
				method : 'post',
				data : {
					role : role,
					module : module,
					action : act,
					_token : token
				},
				success : function(result){
					swal({
                        type : 'success',
                        title : 'Success',
                        text : 'Module : '+module+', Action : '+action+', Added'
                    });
				},
				error : function(er){
                    swal({
                        type : 'error',
                        title : 'Failed',
                        text : 'Failed'
                    });
                }
			});
		}
		else
		{
			// alert('unchecked '+role+'-'+module+'-'+act);
			$.ajax({
				url : '{{ route("access-level.remove-act") }}',
				method : 'post',
				data : {
					role : role,
					module : module,
					action : act,
					_token : token
				},
				success : function(r){
					swal({
                        type : 'success',
                        title : 'Deleted',
                        text : 'Module : '+module+', Action : '+action+', Deleted'
                    });
				},
				error : function(er){
                    swal({
                        type : 'error',
                        title : 'Failed',
                        text : 'Failed'
                    });
                }
			});
		}
	});

</script>
@endpush

resources/views/setting/access-level/index.blade.php
@extends('base.main')
@section('title') Access Role @endsection
@section('page_icon') <i class="fa fa-cog"></i> @endsection
@section('page_title') Access Role @endsection
@section('page_subtitle') list @endsection

@section('content')
    <div class="box box-solid">
        <div class="box-body">
            <table id="datatable" class="table table-hover table-condensed table-bordered">
                <thead>
                    <tr>
                        <th width="50px">No</th>
                        <th>Role</th>
                        <th width="100px">Action</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        $('#datatable').DataTable({
            responsive : true,
            processing : true,
            serverSide : true,
            ajax: "{{ route('table.access-level') }}",
            columns: [
                {data : 'DT_Row_Index', name : 'id'},
                {data : 'role', name : 'role'},
                {data : 'action', name : 'action'}
            ]
        });
    </script>
@endpush